version: '3.8'

services:
  ray-head:
    image: rayproject/ray:latest
    container_name: ray-head
    command: ["ray", "start", "--head", "--port=6379"]
    ports:
      - "6379:6379"
      - "8265:8265"
    networks:
      - ray-network

  ray-worker:
    image: rayproject/ray:latest
    depends_on:
      - ray-head
    command: ["ray", "start", "--address=ray-head:6379"]
    deploy:
      replicas: 3
    networks:
      - ray-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - ray-network
    volumes:
      - mongo_data:/data/db

networks:
  ray-network:
    driver: bridge

volumes:
  mongo_data:
